### ISSUE TITLE
Add support for cflinuxfs4 stack

### ISSUE THREAD

**Issue by jochenehret** [cloudfoundry/staticfile-buildpack-release#1]
Hi Buildpack Developers,

can you please add support for the cflinuxfs4 stack? We have already an experimental ops file for cf-deployment to enable the new stack:
https://github.com/cloudfoundry/cf-deployment/blob/main/operations/experimental/add-cflinuxfs4.yml

There is also a job in the cf-deployment release pipeline which runs CATs with cflinuxfs4:
https://app-runtime-deployments.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/experimental-cats-cflinuxfs4

The current state of the cflinuxfs4 integration in cf-deployment is maintained in this issue:
https://github.com/cloudfoundry/cf-deployment/issues/989

Thanks and Best Regards,

  Jochen on behalf of the ARD WG.

**Comment by arjun024** [comment]
Hi,
The team hasn't yet scheduled work for this but it's in our roadmap

**Comment by brayanhenao** [comment]
Tasks:
* [ ] Build dependency & update Buildpack develop
* [ ] Integrate into buildpacks pipeline
* [ ] Add cflinuxfs4 support to buildpack bosh releases

**Comment by ryanmoran** [comment]
@thitch97 is working on this

**Comment by Gerg** [comment]
Looks like https://github.com/cloudfoundry/staticfile-buildpack/releases/tag/v1.6.0 supports fs4!

**Comment by brayanhenao** [comment]
Yes, as @Gerg commented, staticfile since v1.6.0 supports cflinuxfs4.
